name: Install a command written in Go
description: This action installs the package by go install.
inputs:
  package-path:
    description: Package import path.
    required: false
    default: github.com/${{ github.repository }}
  version:
    description: Package version.
    required: false
    default: latest
  path:
    description: Destination path.
    required: false
    default: ${{ github.workspace }}
outputs:
  target:
    description: Target binary file.
    value: ${{ steps.build.outputs.target }}

runs:
  using: composite
  steps:
  - name: Build a package
    run: |
      echo "GOOS=$(go env GOOS)"
      echo "GOARCH=$(go env GOARCH)"
      bindir="$(go env GOPATH)/bin"
      name="$(basename "$INPUT_PACKAGE_PATH")"

      target="$name"
      if [[ "$(go env GOOS)" = windows ]]
      then
        target="$target.exe"
      fi

      go install "$INPUT_PACKAGE_PATH@$INPUT_VERSION"
      file="$(find "$bindir" -type f -executable -name "$target")"
      mv "$file" "$INPUT_PATH/$target"
      echo target="$target" >>"$GITHUB_OUTPUT"
    env:
      INPUT_PACKAGE_PATH: ${{ inputs.package-path }}
      INPUT_VERSION: ${{ inputs.version }}
      INPUT_PATH: ${{ inputs.path }}
    shell: bash
    id: build
