name: Install a command written in Go
description: This action installs the package by go install.
inputs:
  package-path:
    description: Package import path.
    required: false
    default: github.com/${{ github.repository }}
  version:
    description: Package version.
    required: false
    default: latest
  path:
    description: Destination path.
    required: false
    default: ${{ github.workspace }}
outputs:
  target:
    description: Target binary file.
    value: ${{ steps.build.outputs.target }}

runs:
  using: composite
  steps:
  - name: build
    run: |
      echo "GOOS=$(go env GOOS)"
      echo "GOARCH=$(go env GOARCH)"
      bindir="$(go env GOPATH)/bin"
      name="$(basename "${{ inputs.package-path }}")"

      target="$name"
      if [[ "$(go env GOOS)" = windows ]]
      then
        target="$target.exe"
      fi

      go install "${{ inputs.package-path }}@${{ inputs.version }}"
      file="$(find "$bindir" -type f -executable -name "$target")"
      mv "$file" "${{ inputs.path }}/$target"
      echo target="$target" >>"$GITHUB_OUTPUT"
    id: build
    shell: bash
